# Generated by Django 4.2.19 on 2025-03-07 02:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('part_name', models.CharField(max_length=255)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DismantlingAndRemovalDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('BillOfMaterial', 'Bill of Material'), ('Model3D', 'Model 3D'), ('DismantlingManual', 'Dismantling Manual'), ('RemovalManual', 'Removal Manual'), ('OtherManual', 'Other Manual'), ('Drawing', 'Drawing')], max_length=50)),
                ('mime_type', models.CharField(max_length=50)),
                ('document_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='EndOfLifeInformationEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('waste_prevention', models.FileField(max_length=255, upload_to='')),
                ('separate_collection', models.FileField(max_length=255, upload_to='')),
                ('information_on_collection', models.FileField(max_length=255, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RecycledContentEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('pre_consumer_share', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recycled_material', models.CharField(choices=[('Cobalt', 'Cobalt'), ('Nickel', 'Nickel'), ('Lithium', 'Lithium'), ('Lead', 'Lead')], max_length=50)),
                ('post_consumer_share', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyMeasuresEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('safety_instructions', models.FileField(max_length=255, upload_to='')),
                ('extinguishing_agent', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SparePartSupplierEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('name_of_supplier', models.CharField(max_length=255)),
                ('email_address_of_supplier', models.EmailField(max_length=254)),
                ('supplier_web_address', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('address_of_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circularity.postaladdress')),
                ('components', models.ManyToManyField(related_name='suppliers', to='circularity.componententity')),
            ],
        ),
        migrations.CreateModel(
            name='Circularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('circularity_id', models.CharField(max_length=255, unique=True)),
                ('renewable_content', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hash_signature', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('dismantling_and_removal_information', models.ManyToManyField(related_name='circularities', to='circularity.dismantlingandremovaldocumentation')),
                ('end_of_life_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circularity.endoflifeinformationentity')),
                ('recycled_content', models.ManyToManyField(related_name='circularities', to='circularity.recycledcontententity')),
                ('safety_measures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circularity.safetymeasuresentity')),
                ('spare_part_sources', models.ManyToManyField(related_name='circularities', to='circularity.sparepartsupplierentity')),
            ],
        ),
    ]
