# Generated by Django 4.2.19 on 2025-03-07 02:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformationEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PostalAddressEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('address_country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralProductInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('battery_id', models.CharField(max_length=255, unique=True)),
                ('product_identifier', models.CharField(max_length=255, unique=True)),
                ('battery_passport_identifier', models.CharField(max_length=255, unique=True)),
                ('battery_category', models.CharField(choices=[('lmt', 'LMT'), ('ev', 'EV'), ('industrial', 'Industrial'), ('stationary', 'Stationary')], max_length=50)),
                ('manufacturing_date', models.DateField()),
                ('battery_status', models.CharField(choices=[('Original', 'Original'), ('Repurposed', 'Repurposed'), ('Reused', 'Reused'), ('Remanufactured', 'Remanufactured'), ('Waste', 'Waste')], max_length=50)),
                ('battery_mass', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('putting_into_service', models.DateField()),
                ('warranty_period', models.DateField()),
                ('hash_signature', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('manufacturer_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='generalproductinfo.contactinformationentity')),
                ('manufacturing_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_places', to='generalproductinfo.postaladdressentity')),
                ('operator_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='generalproductinfo.contactinformationentity')),
            ],
        ),
        migrations.AddField(
            model_name='contactinformationentity',
            name='postal_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalproductinfo.postaladdressentity'),
        ),
    ]
