# Generated by Django 4.2.19 on 2025-03-17 04:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('cell_id', models.CharField(help_text='A user-friendly ID for the cell or cell batch.', max_length=100, unique=True)),
                ('cell_type', models.CharField(choices=[('Cylindrical (18650)', 'Cylindrical (18650)'), ('Cylindrical (21700)', 'Cylindrical (21700)'), ('pouch', 'Pouch'), ('prismatic', 'Prismatic'), ('other', 'Other')], max_length=30)),
                ('number_of_cells', models.PositiveIntegerField(default=1, help_text='If grouping multiple identical cells under this record.')),
                ('manufacturing_date', models.DateField(blank=True, help_text='Date of manufacturing (if known).', null=True)),
                ('chemistry', models.CharField(choices=[('LFP', 'Lithium Iron Phosphate (LFP)'), ('NMC622', 'NMC (6:2:2)'), ('NMC811', 'NMC (8:1:1)'), ('NCA', 'Nickel Cobalt Aluminum (NCA)'), ('other', 'Other')], default='other', max_length=10)),
                ('nominal_voltage', models.FloatField(help_text='Nominal voltage (V) per cell.')),
                ('rated_capacity_ah', models.FloatField(help_text='Rated capacity (Ah) per cell.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('manufacturer', models.ForeignKey(help_text='Which company produced these cells?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battery_cells', to='common.contactinformation')),
            ],
        ),
    ]
