# Generated by Django 4.2.19 on 2025-02-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyChainDueDiligence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supply_chain_due_diligence_report', models.TextField()),
                ('third_party_assurances', models.TextField()),
                ('supply_chain_indices', models.FloatField(default=0)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
