# Generated by Django 4.2.19 on 2025-02-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duediligence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplychainduediligence',
            name='supply_chain_due_diligence_report',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='supplychainduediligence',
            name='third_party_aussurances',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
