# Generated by Django 4.2.19 on 2025-02-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duediligence', '0002_alter_supplychainduediligence_supply_chain_due_diligence_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplychainduediligence',
            name='supply_chain_indicies',
        ),
        migrations.RemoveField(
            model_name='supplychainduediligence',
            name='third_party_aussurances',
        ),
        migrations.AddField(
            model_name='supplychainduediligence',
            name='supply_chain_indices',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supplychainduediligence',
            name='third_party_assurances',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplychainduediligence',
            name='supply_chain_due_diligence_report',
            field=models.TextField(),
        ),
    ]
