# Generated by Django 5.1.5 on 2025-02-12 09:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelingEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labeling_symbol', models.URLField()),
                ('labeling_meaning', models.TextField()),
                ('labeling_subject', models.CharField(choices=[('SeparateCollection', 'Separate Collection'), ('HazardousMaterial', 'Hazardous Material'), ('CarbonFootPrint', 'Carbon Footprint'), ('ExtinguishingAgent', 'Extinguishing Agent')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Labeling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('declaration_of_conformity', models.URLField()),
                ('result_of_test_report', models.URLField()),
                ('labels', models.ManyToManyField(related_name='labelings', to='labeling.labelingentity')),
            ],
        ),
    ]
