# Generated by Django 4.2.19 on 2025-02-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelingEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labeling_symbol', models.TextField()),
                ('labeling_meaning', models.JSONField()),
                ('labeling_subject', models.CharField(choices=[('SeparateCollection', 'Separate Collection'), ('HazardousMaterial', 'Hazardous Material'), ('CarbonFootPrint', 'Carbon Footprint'), ('ExtinguishingAgent', 'Extinguishing Agent')], max_length=50)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labeling',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('declaration_of_conformity', models.TextField()),
                ('result_of_test_report', models.TextField()),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('labels', models.ManyToManyField(related_name='labelings', to='labeling.labelingentity')),
            ],
        ),
    ]
