# Generated by Django 5.1.5 on 2025-02-12 09:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprintPerLifecycleStageEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifecycle_stage', models.CharField(choices=[('RawMaterialExtraction', 'Raw Material Extraction'), ('MainProduction', 'Main Production'), ('Distribution', 'Distribution'), ('Recycling', 'Recycling')], max_length=50)),
                ('carbon_footprint', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CarbonFootprintForBatteries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('battery_carbon_footprint', models.FloatField()),
                ('carbon_footprint_performance_class', models.CharField(max_length=255)),
                ('carbon_footprint_study', models.URLField()),
                ('absolute_carbon_footprint', models.FloatField(blank=True, null=True)),
                ('carbon_footprint_per_lifecycle_stage', models.ManyToManyField(related_name='batteries', to='carbonfootprints.carbonfootprintperlifecyclestageentity')),
            ],
        ),
    ]
