# Generated by Django 4.2.19 on 2025-02-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprintPerLifecycleStageEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifecycle_stage', models.CharField(choices=[('RawMaterialExtraction', 'Raw Material Extraction'), ('MainProduction', 'Main Production'), ('Distribution', 'Distribution'), ('Recycling', 'Recycling')], max_length=50)),
                ('carbon_footprint', models.FloatField()),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarbonFootprintForBatteries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('battery_carbon_footprint', models.FloatField()),
                ('carbon_footprint_performance_class', models.CharField(max_length=255)),
                ('carbon_footprint_study', models.TextField()),
                ('absolute_carbon_footprint', models.FloatField(blank=True, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('carbon_footprint_per_lifecycle_stage', models.ManyToManyField(related_name='batteries', to='carbonfootprints.carbonfootprintperlifecyclestageentity')),
            ],
        ),
    ]
