# Generated by Django 4.2.19 on 2025-03-07 02:24

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprintPerLifecycleStageEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('lifecycle_stage', models.CharField(choices=[('RawMaterialExtraction', 'Raw Material Extraction'), ('MainProduction', 'Main Production'), ('Distribution', 'Distribution'), ('Recycling', 'Recycling')], max_length=50)),
                ('carbon_footprint', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CarbonFootprintForBatteries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('battery_id', models.CharField(max_length=255, unique=True)),
                ('battery_carbon_footprint', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('carbon_footprint_performance_class', models.CharField(max_length=255)),
                ('carbon_footprint_study', models.FileField(upload_to='')),
                ('absolute_carbon_footprint', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('hash_signature', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('carbon_footprint_per_lifecycle_stage', models.ManyToManyField(related_name='batteries', to='carbonfootprints.carbonfootprintperlifecyclestageentity')),
            ],
        ),
    ]
