# Generated by Django 5.1.5 on 2025-02-12 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryTechnicalPropertiesEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated_maximum_power', models.FloatField()),
                ('power_capability_ratio', models.FloatField()),
                ('rated_energy', models.FloatField()),
                ('expected_number_of_cycles', models.BigIntegerField()),
                ('initial_self_discharge', models.FloatField()),
                ('roundtrip_efficiency', models.FloatField()),
                ('rated_capacity', models.FloatField()),
                ('expected_lifetime', models.IntegerField()),
                ('nominal_voltage', models.FloatField()),
                ('minimum_voltage', models.FloatField()),
                ('maximum_voltage', models.FloatField()),
                ('capacity_threshold_for_exhaustion', models.FloatField()),
                ('lifetime_reference_test', models.URLField()),
                ('c_rate_life_cycle_test', models.FloatField()),
                ('temperature_range_idle_state', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CapacityFadeEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CapacityThroughputEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentSelfDischargingRateEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EvolutionOfSelfDischargeEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InternalResistanceEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ohmic_resistance', models.FloatField()),
                ('battery_component', models.CharField(choices=[('pack', 'Pack'), ('module', 'Module'), ('cell', 'Cell')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InternalResistanceIncreaseEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('last_update', models.DateTimeField()),
                ('battery_component', models.CharField(choices=[('pack', 'Pack'), ('module', 'Module'), ('cell', 'Cell')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NegativeEventEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative_event', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfFullCyclesEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PowerCapabilityAtEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_soc', models.FloatField()),
                ('power_capability_at', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RemainingCapacityEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RemainingEnergyEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RemainingPowerCapabilityEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RemainingRoundTripEnergyEfficiencyEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StateOfCertifiedEnergyEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StateOfChargeEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureConditionsEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_extreme_high_temp', models.FloatField()),
                ('time_extreme_low_temp', models.FloatField()),
                ('time_extreme_high_temp_charging', models.FloatField()),
                ('time_extreme_low_temp_charging', models.FloatField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BatteryConditionEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_throughput', models.FloatField()),
                ('power_fade', models.FloatField()),
                ('round_trip_efficiency_fade', models.FloatField()),
                ('round_trip_efficiency_at_50_percent_cycle_life', models.FloatField()),
                ('capacity_fade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.capacityfadeentity')),
                ('capacity_throughput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.capacitythroughputentity')),
                ('current_self_discharging_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.currentselfdischargingrateentity')),
                ('evolution_of_self_discharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.evolutionofselfdischargeentity')),
                ('number_of_full_cycles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.numberoffullcyclesentity')),
                ('remaining_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.remainingcapacityentity')),
                ('remaining_energy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.remainingenergyentity')),
                ('remaining_round_trip_energy_efficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.remainingroundtripenergyefficiencyentity')),
                ('state_of_certified_energy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.stateofcertifiedenergyentity')),
                ('state_of_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.stateofchargeentity')),
                ('temperature_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.temperatureconditionsentity')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceAndDurability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('battery_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.batteryconditionentity')),
                ('battery_technical_properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.batterytechnicalpropertiesentity')),
            ],
        ),
    ]
