# Generated by Django 4.2.19 on 2025-03-07 02:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryChemistryEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('clear_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryLocationEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('component_name', models.CharField(max_length=255)),
                ('component_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryMaterialEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('battery_material_identifier', models.CharField(max_length=50, unique=True)),
                ('battery_material_name', models.CharField(max_length=255)),
                ('battery_material_mass', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_critical_raw_material', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('battery_material_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.batterylocationentity')),
            ],
        ),
        migrations.CreateModel(
            name='HazardousSubstanceEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('hazardous_substance_class', models.CharField(choices=[('AcuteToxicity', 'Acute Toxicity'), ('SkinCorrosionOrIrritation', 'Skin Corrosion or Irritation'), ('EyeDamageOrIrritation', 'Eye Damage or Irritation')], max_length=50)),
                ('hazardous_substance_name', models.CharField(max_length=255)),
                ('hazardous_substance_concentration', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hazardous_substance_impact', models.JSONField()),
                ('hazardous_substance_identifier', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('hazardous_substance_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.batterylocationentity')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('material_composition_id', models.CharField(max_length=255, unique=True)),
                ('hash_signature', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('battery_chemistry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.batterychemistryentity')),
                ('battery_materials', models.ManyToManyField(related_name='materials', to='materials.batterymaterialentity')),
                ('hazardous_substances', models.ManyToManyField(related_name='hazardous_substances', to='materials.hazardoussubstanceentity')),
            ],
        ),
    ]
