# Generated by Django 4.2.19 on 2025-03-17 04:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryChemistryEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('clear_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryLocationEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('component_name', models.CharField(max_length=255)),
                ('component_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryMaterialEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('battery_material_identifier', models.CharField(max_length=50, unique=True)),
                ('battery_material_name', models.CharField(max_length=255)),
                ('battery_material_mass', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_critical_raw_material', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('battery_material_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.batterylocationentity')),
            ],
        ),
        migrations.CreateModel(
            name='ESGPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('esg_performance_summary', models.CharField(choices=[('High', 'High ESG Compliance'), ('Medium', 'Medium ESG Compliance'), ('Low', 'Low ESG Compliance'), ('Reported', 'Reported but not classified')], default='Reported', max_length=50)),
                ('carbon_footprint', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Reported', 'Reported')], default='Reported', max_length=50)),
                ('renewable_energy_use', models.CharField(choices=[('0-25%', '0-25%'), ('26-50%', '26-50%'), ('51-75%', '51-75%'), ('76-100%', '76-100%'), ('Reported', 'Reported')], default='Reported', max_length=50)),
                ('water_consumption', models.CharField(choices=[('Minimal', 'Minimal'), ('Moderate', 'Moderate'), ('Excessive', 'Excessive'), ('Reported', 'Reported')], default='Reported', max_length=100)),
                ('social_impact', models.CharField(choices=[('Fair trade certified', 'Fair trade certified'), ('Ethical sourcing', 'Ethical sourcing'), ('No certification', 'No certification'), ('Reported', 'Reported')], default='Reported', max_length=255)),
                ('worker_safety_standards', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Reported', 'Reported')], default='Reported', max_length=100)),
                ('governance_compliance', models.CharField(choices=[('ISO 14001', 'ISO 14001'), ('EU Battery Directive', 'EU Battery Directive'), ('REACH Certified', 'REACH Certified'), ('No compliance', 'No compliance'), ('Reported', 'Reported')], default='Reported', max_length=255)),
                ('recycling_efficiency', models.CharField(choices=[('0-25%', '0-25%'), ('26-50%', '26-50%'), ('51-75%', '51-75%'), ('76-100%', '76-100%'), ('Reported', 'Reported')], default='Reported', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HazardousSubstanceEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('hazardous_substance_class', models.CharField(choices=[('AcuteToxicity', 'Acute Toxicity'), ('SkinCorrosionOrIrritation', 'Skin Corrosion or Irritation'), ('EyeDamageOrIrritation', 'Eye Damage or Irritation'), ('Carcinogenic', 'Carcinogenic'), ('SkinIrritation', 'Skin Irritation'), ('Skin/EyeIrritant', 'Skin/Eye Irritant'), ('Corrosive', 'Corrosive'), ('RespiratorySensitizer', 'Respiratory Sensitizer'), ('ReproductiveToxicity', 'Reproductive Toxicity'), ('Mutagenic', 'Mutagenic')], max_length=50)),
                ('hazardous_substance_name', models.CharField(max_length=255)),
                ('hazardous_substance_concentration', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hazardous_substance_impact', models.JSONField()),
                ('hazardous_substance_identifier', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('hazardous_substance_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.batterylocationentity')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_short', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('semantic_id', models.URLField(blank=True, null=True)),
                ('material_composition_id', models.CharField(max_length=255, unique=True)),
                ('traceability', models.BooleanField(default=False)),
                ('tracing_period_start', models.DateField(blank=True, null=True)),
                ('tracing_period_end', models.DateField(blank=True, null=True)),
                ('physical_amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('traced_amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('esg_performance_summary', models.CharField(choices=[('High', 'High ESG Compliance'), ('Medium', 'Medium ESG Compliance'), ('Low', 'Low ESG Compliance'), ('Reported', 'Reported but not classified')], default='Reported', max_length=50)),
                ('hash_signature', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('battery_chemistry', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='materials.batterychemistryentity')),
                ('battery_materials', models.ManyToManyField(related_name='materials', to='materials.batterymaterialentity')),
                ('esg_performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.esgperformance')),
                ('first_traced_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_traced', to='materials.batterymaterialentity')),
                ('hazardous_substances', models.ManyToManyField(related_name='hazardous_substances', to='materials.hazardoussubstanceentity')),
                ('manufacturer', models.ForeignKey(help_text='Which company produced these cells?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battery_materials', to='common.contactinformation')),
                ('second_traced_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_traced', to='materials.batterymaterialentity')),
            ],
        ),
    ]
