# Generated by Django 5.1.5 on 2025-02-12 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryChemistryEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('clear_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryLocationEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=255)),
                ('component_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryMaterialEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_material_identifier', models.CharField(max_length=20, unique=True)),
                ('battery_material_name', models.CharField(max_length=255)),
                ('battery_material_mass', models.FloatField()),
                ('is_critical_raw_material', models.BooleanField()),
                ('battery_material_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.batterylocationentity')),
            ],
        ),
        migrations.CreateModel(
            name='HazardousSubstanceEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazardous_substance_class', models.CharField(choices=[('AcuteToxicity', 'Acute Toxicity'), ('SkinCorrosionOrIrritation', 'Skin Corrosion or Irritation'), ('EyeDamageOrIrritation', 'Eye Damage or Irritation')], max_length=50)),
                ('hazardous_substance_name', models.CharField(max_length=255)),
                ('hazardous_substance_concentration', models.FloatField()),
                ('hazardous_substance_impact', models.JSONField()),
                ('hazardous_substance_identifier', models.CharField(max_length=20, unique=True)),
                ('hazardous_substance_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.batterylocationentity')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialComposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('battery_chemistry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.batterychemistryentity')),
                ('battery_materials', models.ManyToManyField(related_name='materials', to='materials.batterymaterialentity')),
                ('hazardous_substances', models.ManyToManyField(related_name='hazardous_substances', to='materials.hazardoussubstanceentity')),
            ],
        ),
    ]
